# Generated by Django 5.2.11 on 2026-02-20 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=400)),
                ('category', models.CharField(choices=[('Електроника', 'Електроника'), ('Дом. Потреби', 'Домашни Потреби'), ('Животни', 'Животни'), ('Други', 'Други')], max_length=30)),
                ('image_url', models.URLField()),
                ('status_gift', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='accounts.profile')),
                ('tags', models.ManyToManyField(blank=True, to='gifts.tag')),
            ],
        ),
    ]
