# Generated by Django 5.2.11 on 2026-02-21 02:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='description',
            field=models.TextField(max_length=400, validators=[django.core.validators.MinLengthValidator(20, message='Описанието трябва да съдържа поне 20 символа!')]),
        ),
        migrations.AlterField(
            model_name='gift',
            name='title',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(10, message='Заглавието трябва да съдържа поне 10 символа!'), django.core.validators.RegexValidator(message='Заглавието трябва да съдържа само букви и цифри', regex='^[A-Za-z0-9_ ]+$')]),
        ),
    ]
