# Generated by Django 5.2.11 on 2026-02-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0002_alter_gift_description_alter_gift_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='tags',
            field=models.ManyToManyField(related_name='gifts', to='gifts.tag'),
        ),
    ]
