# Generated by Django 5.2.11 on 2026-02-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0003_alter_gift_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='tags',
        ),
    ]
