# Generated by Django 5.2.11 on 2026-02-21 01:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(4, message='Името трябва да съдържа поне 4 символа!'), django.core.validators.RegexValidator(message='Името трябва да съдържа само букви!', regex='^[A-Za-z]+$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(4, message='Фамилното име трябва да съдържа поне 4 символа!'), django.core.validators.RegexValidator(message='Името трябва да съдържа само букви!', regex='^[A-Za-z]+$')]),
        ),
    ]
